### ISSUE TITLE
Comparing Spafe with librosa and surfboard

### ISSUE THREAD

**Issue by hadware** [SuperKogito/spafe#45]
This is both a comment for the paper and for the repo's README: the first python lib that came to my mind when I saw the review request was librosa. Could you - in the paper's statement of need - elaborate on why this lib is relevant in comparison to what librosa already provides? This would neatly fit with the other challengers (namely, Bob, SpeechPy and python_speech_features). The same argument could be made with the less well-known [surfboard](https://github.com/novoic/surfboard).

As a side note and quasi-request, it'd be nice to have such a comparison outlined in the README. If I were someone that came across this repo, i'd like to know how this is not "yet another audio feature extraction lib", and how this one might fit my needs (especially in comparison to other libs). If I were of bad faith, i'd say i'd like to see a bit of marketing  :smiling_imp:

**Comment by hbredin** [comment]
I came here to make the same comment about adding a comparison with `librosa` (and @hadware beat me to it).

**Comment by SuperKogito** [comment]
I considered this when writing the paper but I felt that a comparison is unfair to Spafe, since Librosa was written by more experienced developers (well established and optimized), did more than just extract features (e.g. audio reconstruction) and mostly focused on different types of features (eg. temporal).

**Comment by hbredin** [comment]
The fact that you knew about `librosa` and chose not to mention it in the paper is actually unfair to `librosa`, not the other way around. 

As you mentioned yourself, `librosa` is _"well established and optimized"_ and is the _de facto standard_ for audio and speech feature extraction. The reviewer checklist specifically asks us, reviewers, to check whether _"the authors describe how this software compares to other commonly-used packages_. As of today, the answer is "no" because of this "omission".

**Comment by SuperKogito** [comment]
I tried to address this in #51 
Librosa is different and as one of its contributors and users I can say that Spafe is different and provides a wide variety of features not available in Librosa and vice versa. Even the MFCC implementations are actually different since Spafe uses DFT and Librosa uses STFT. 
Surfboard does not include the feature extractions available in Spafe, and its MFCC implementation is simply a wrapper around Librosa's implementation.

**Comment by hadware** [comment]
This solves it for me, I'll let @hbredin put his stamp of approval as well :)

**Comment by hbredin** [comment]
Thanks @SuperKogito! This issue can be closed.

**Comment by SuperKogito** [comment]
closed in #51

**Comment by hadware** [comment]
I'm not reopening this issue, but just a small comment: the wall of text in the ["Why use spafe"](https://github.com/SuperKogito/spafe#why-use-spafe) section could (I think) gain a lot by being given a bit more visual structure (bullet points for instance).
